### ISSUE TITLE
Some of the recipes do not have data and just say "too many requests"

### ISSUE THREAD

**Issue by komal98** [dpapathanasiou/recipes#1]
![image](https://user-images.githubusercontent.com/20492468/80830113-07656780-8c06-11ea-9e30-92243bfab7e4.png)

**Comment by dpapathanasiou** [comment]
Thank you for noticing, and letting me know.

I'll scan the json data for that title, and retry the affected urls with a less aggressive [crawling strategy](https://github.com/dpapathanasiou/recipebook#crawling). 

If you can help me compile a list, and retry them yourself, please feel free to make a [pull request](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests) :smile:

**Comment by dpapathanasiou** [comment]
Hey @komal98, you inspired me to update the [recipebook code to Python3](https://github.com/dpapathanasiou/recipebook/releases/tag/v1.6).

Now I can run the missing urls in the background, and eventually grab them all.

**Comment by dpapathanasiou** [comment]
Closed by 48268785a13d598a87de2e75c525056d00202e54

**Comment by komal98** [comment]
Thanks!:) @dpapathanasiou
